#! /usr/bin/env bash

# rbw git-credential helper
# Based on https://github.com/lastpass/lastpass-cli/blob/master/contrib/examples/git-credential-lastpass

# A credential helper for git to retrieve usernames and passwords from rbw.
# For general usage, see https://git-scm.com/docs/gitcredentials.
# Here's a quick version:
# 1. Put this somewhere in your path.
# 2. git config --global credential.helper rbw

declare -A params

if [ "$1" == "get" ]; then
    read -r line
    while [ -n "$line" ]; do
        key=${line%%=*}
        value=${line#*=}
        params[$key]=$value
        read -r line
    done

    if [ "${params['protocol']}" != "https" ]; then
        exit
    fi

    if [ -z "${params["host"]}" ]; then
        exit
    fi

    if ! rbw ls >/dev/null 2>&1; then
        echo "Please login to rbw to use git credential helper" >/dev/stderr
        exit
    fi

    rbw sync >/dev/null 2>&1

    bitwarden_item=$(rbw get --full "${params['host']}")

    user=$(echo "${bitwarden_item}" | grep "Username:" | cut -d' ' -f2-)
    pass=$(echo "${bitwarden_item}" | grep "api_key:" | cut -d' ' -f2-)

    if [ -z "$user" ] || [ -z "$pass" ]; then
        echo "Couldn't find host in rbw DB." >/dev/stderr
        exit
    fi

    echo username="$user"
    echo password="$pass"
fi
