ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#314952"

# match_prev_cmd needs the options HIST_IGNORE_ALL_DUPS and HIST_EXPIRE_DUPS_FIRST to be unset
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history)
# ZSH_AUTOSUGGEST_STRATEGY=(history)

# echo "BEFORE: ${ZSH_AUTOSUGGEST_ACCEPT_WIDGETS}"
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=("${(@)ZSH_AUTOSUGGEST_ACCEPT_WIDGETS:#forward-char}")
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=("${(@)ZSH_AUTOSUGGEST_ACCEPT_WIDGETS:#vi-forward-char}")
# echo "AFTER: ${ZSH_AUTOSUGGEST_ACCEPT_WIDGETS}"

# echo "----------------------------------------"

# echo "BEFORE: ${ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS}"
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS+=(forward-char)
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS+=(vi-forward-char)
# echo "AFTER: ${ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS}"
