[tools]
ansible = "11.6.0"
ansible-core = "2.18.6"
aws-cli = "2.27.21"
node = "24.1.0"
python = "3.13.4"
terraform = "1.7.4"
terraform-ls = "0.36.4"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
